version: '3.1'
services:
  spring-boot-k8s-demo:
    build: .
    container_name: spring-boot-k8s-demo
    ports:
      - "18080:8080"
      - "18787:8787"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: test
      DB_USERNAME: siva
      DB_PASSWORD: sivalabs
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
      MYSQL_USER: siva
      MYSQL_PASSWORD: sivalabs
