apiVersion: v1
kind: Service
metadata:
  name: k8sdemo-svc
spec:
  selector:
    app: k8sdemo-pod
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sdemo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sdemo-pod
  template:
    metadata:
      labels:
        app: k8sdemo-pod
    spec:
      containers:
      - name: k8sdemo
        image: sivaprasadreddy/spring-boot-k8s-demo
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: mysql_host
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: mysql_port
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: mysql_database
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: password
        ports:
        - containerPort: 8080
---
