---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: default
data:
  mysql_host: mysql
  mysql_port: "3306"
  mysql_database: test
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  root-password: YWRtaW4= # admin
  username: c2l2YQ== # siva
  password: c2l2YWxhYnM= # sivalabs
---
