apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: k8sdemo
  labels:
    app: k8sdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sdemo
  template:
    metadata:
      labels:
        app: k8sdemo
    spec:
      containers:
      - name: k8sdemo
        image: sivaprasadreddy/spring-boot-k8s-demo
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: k8sdemo
  labels:
    app: k8sdemo
spec:
  selector:
    app: k8sdemo
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort